name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    env:
      CODACY_API_TOKEN: ${secret.CODACY_ACCOUT_TOKEN}
      CODACY_ORGANIZATION_PROVIDER: gh
      CODACY_USERNAME: coniadev
      CODACY_PROJECT_NAME: core
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pcov, curl, xml, zip, mbstring, json

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install packages with composer
        run: composer install

      - name: Run tests, static type checker and linter
        run: composer github

      - name: Upload coverage report to Codacy
        runt: bash <(curl -Ls https://coverage.codacy.com/get.sh)
